version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.common
    working_dir: /app/backend_python
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/app
      REDIS_URL: redis://redis:6379/0
    depends_on: [db, redis]
    command: >
      uvicorn backend_python.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  workers:
    build:
      context: ..
      dockerfile: infra/Dockerfile.common
    working_dir: /app/backend_python
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/app
      REDIS_URL: redis://redis:6379/0
    depends_on: [db, redis]
    command: >
      sh -c "
        python -m backend_python.chat.service.background_tasks.run_scheduled &
        python -m backend_python.chat.service.background_tasks.run_workers
      "

  ws:
    image: golang:1.24
    volumes:
      - ..:/app
    working_dir: /app
    depends_on: [redis]
    environment:
      GOTOOLCHAIN: auto
    command: >
      sh -c "go mod download &&
            go install github.com/air-verse/air@latest &&
            air -c .air.docker.toml"
    ports:
      - "8080:8080"

  web:
    image: node:20
    volumes:
      - ..:/app
    working_dir: /app/frontend
    environment:
      VITE_API_URL: http://api:8000
      VITE_WS_URL: ws://ws:8080
    command: >
      sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"

volumes:
  pgdata:
