"""initial clean state

Revision ID: 16959ca0cec6
Revises: 3ebd3a050f68
Create Date: 2025-11-10 19:15:43.598044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16959ca0cec6'
down_revision: Union[str, None] = '3ebd3a050f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('key', sa.String(), nullable=False))
    op.add_column('attachments', sa.Column('type', sa.String(), nullable=False))
    op.add_column('attachments', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('attachments', sa.Column('mime', sa.String(), nullable=True))
    op.add_column('attachments', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('duration', sa.Float(), nullable=True))
    op.drop_column('attachments', 'filesize')
    op.drop_column('attachments', 'filetype')
    op.drop_column('attachments', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attachments', sa.Column('filetype', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attachments', sa.Column('filesize', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('attachments', 'duration')
    op.drop_column('attachments', 'height')
    op.drop_column('attachments', 'width')
    op.drop_column('attachments', 'mime')
    op.drop_column('attachments', 'size')
    op.drop_column('attachments', 'type')
    op.drop_column('attachments', 'key')
    # ### end Alembic commands ###
