"""add original_name to attachments

Revision ID: 2aeadddfa910
Revises: 6046e4e827c9
Create Date: 2025-08-02 16:13:48.016365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aeadddfa910'
down_revision: Union[str, None] = '6046e4e827c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('original_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'original_name')
    # ### end Alembic commands ###
