"""Add pinned and reply_to

Revision ID: 997c931bcfd6
Revises: e9aaced482fb
Create Date: 2025-07-15 14:22:04.139082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997c931bcfd6'
down_revision: Union[str, None] = 'e9aaced482fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('reply_to_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'is_pinned')
    # ### end Alembic commands ###
