"""Add chat_key to chats

Revision ID: e9aaced482fb
Revises: a0e8cae76273
Create Date: 2025-07-07 12:00:08.627021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9aaced482fb'
down_revision: Union[str, None] = 'a0e8cae76273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_key', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'chats', ['chat_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_column('chats', 'chat_key')
    # ### end Alembic commands ###
