"""add FriendLink table

Revision ID: ea3a5800ab6f
Revises: cc62cda1a18f
Create Date: 2025-08-12 20:55:48.656178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3a5800ab6f'
down_revision: Union[str, None] = 'cc62cda1a18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('user1_id < user2_id', name='ck_friend_pair_order'),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='uc_friend_pair_single')
    )
    op.create_index(op.f('ix_friend_links_requested_by'), 'friend_links', ['requested_by'], unique=False)
    op.create_index(op.f('ix_friend_links_status'), 'friend_links', ['status'], unique=False)
    op.create_index(op.f('ix_friend_links_user1_id'), 'friend_links', ['user1_id'], unique=False)
    op.create_index(op.f('ix_friend_links_user2_id'), 'friend_links', ['user2_id'], unique=False)
    op.create_index('ix_friend_links_users', 'friend_links', ['user1_id', 'user2_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_friend_links_users', table_name='friend_links')
    op.drop_index(op.f('ix_friend_links_user2_id'), table_name='friend_links')
    op.drop_index(op.f('ix_friend_links_user1_id'), table_name='friend_links')
    op.drop_index(op.f('ix_friend_links_status'), table_name='friend_links')
    op.drop_index(op.f('ix_friend_links_requested_by'), table_name='friend_links')
    op.drop_table('friend_links')
    # ### end Alembic commands ###
