root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "venv", ".git"]
  include_ext = ["go"]
  log = "build-errors.log"
  kill_delay = "0s"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false